
export const products = [
  {
    id: 1,
    name:'Wireless Headphones',
    category: 'Electronics',
    price: 2999,
    rating: 4.5,
    inStock: true,
  },
  {
    id: 2,
    name:'Running Shoes',
    category: 'Fashion',
    price: 3499,
    rating: 4.2,
    inStock: true,
  },
  {
    id: 3,
    name: 'Coffee Maker',
    category: 'Home',
    price: 5999,
    rating: 4.8,
    inStock: false,
  },
  {
    id: 4,
    name: 'Laptop Bag',
    category: 'Fashion',
    price: 1499,
    rating: 4.0,
    inStock: true,
  },
  {
    id: 5,
    name: 'Smart Watch',
    category: 'Electronics',
    price: 8999,
    rating: 4.6,
    inStock: true,
  },
  {
    id: 6,
    name: 'Desk Lamp',
    category: 'Home',
    price: 1299,
    rating: 4.3,
    inStock: true,
  },
  {
    id: 7,
    name: 'Bluetooth Speaker',
    category: 'Electronics',
    price: 1999,
    rating: 4.4,
    inStock: true,
  },
  {
    id: 8,
    name: 'Yoga Mat',
    category: 'Sports',
    price: 899,
    rating: 4.1,
    inStock: true,
  },
  {
    id: 9,
    name: 'Water Bottle',
    category: 'Sports',
    price: 499,
    rating: 4.7,
    inStock: true,
  },
  {
    id: 10,
    name: 'Wall Clock',
    category: 'Home',
    price: 1799,
    rating: 4.0,
    inStock: false,
  },
  {
    id: 11,
    name: 'Sunglasses',
    category: 'Fashion',
    price: 2499,
    rating: 4.5,
    inStock: true,
  },
  {
    id: 12,
    name: 'Gaming Mouse',
    category: 'Electronics',
    price: 1899,
    rating: 4.9,
    inStock: true,
  },
  {
    id: 13,
    name: 'Mechanical Keyboard',
    category: 'Electronics',
    price: 4500,
    rating: 4.8,
    inStock: false,
  },
  {
    id: 14,
    name: 'USB-C Hub',
    category: 'Electronics',
    price: 1200,
    rating: 4.2,
    inStock: true,
  },
  {
    id: 15,
    name: 'Winter Jacket',
    category: 'Fashion',
    price: 4999,
    rating: 4.6,
    inStock: false,
  },
  {
    id: 16,
    name: 'Leather Belt',
    category: 'Fashion',
    price: 999,
    rating: 4.1,
    inStock: true,
  },
  {
    id: 17,
    name: 'Air Purifier',
    category: 'Home',
    price: 12500,
    rating: 4.7,
    inStock: false,
  },
  {
    id: 18,
    name: 'Cotton Bedspread',
    category: 'Home',
    price: 2200,
    rating: 4.3,
    inStock: true,
  },
  {
    id: 19,
    name: 'Adjustable Dumbbells',
    category: 'Sports',
    price: 8500,
    rating: 4.9,
    inStock: false,
  },
  {
    id: 20,
    name: 'Jump Rope',
    category: 'Sports',
    price: 350,
    rating: 4.0,
    inStock: true,
  },
  {
    id: 21,
    name: 'Monitor Stand',
    category: 'Electronics',
    price: 2500,
    rating: 4.4,
    inStock: false,
  },
  {
    id: 22,
    name: 'Denim Jeans',
    category: 'Fashion',
    price: 2999,
    rating: 4.4,
    inStock: false,
  },
  {
    id: 23,
    name: 'Scented Candle Set',
    category: 'Home',
    price: 799,
    rating: 4.5,
    inStock: true,
  },
  {
    id: 24,
    name: 'Tennis Racket',
    category: 'Sports',
    price: 3200,
    rating: 4.2,
    inStock: false,
  }
]